Interface and Logic
akshay-narkar/Todo-Collab pull request #1
Opened 2021-05-19 08:45 UTC by akshay-narkar

## What?
Creating a Todolist app to create lists, add tasks and edit tasks using Javascript & Webpack
## Why?
Part of collaborative project at Javascript at Microverse
## How?
Mentioned in Readme

2021-05-19 14:20 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Good job by using ES6 syntax :+1: 
- Good job by using localStorage :100: 

To improve :factory_worker: [REQUIRED]:

- [x]  [REQUIRED] As your readme file is the first thing that users check, please make sure that your MIT link works.
- [ ]  [REQUIRED] I got an error (Uncaught TypeError: f is null) when I create a task in the `Default project`. It will be nice if you fix it.
![1](https://user-images.githubusercontent.com/58552748/118828306-d1a12880-b8c5-11eb-9883-93d49cdb8915.gif)

- [ ]  [REQUIRED] Please, keep all the styling logic in CSS files.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/styling_requirement.png) from Pathwright)
- [ ]  [REQUIRED] **- Task:** It has a title. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- **Interface:**  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ]  [REQUIRED] User can edit the details of a to-do item
- [ ]  [REQUIRED] User can delete a to-do

Nice to have:

- [ ] 

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-05-19 14:20 UTC, rindrajosia commented on src/modules/project.js
> +  addTaskBtn.style.display = 'block';
Here for example you can create a CSS Class called .block and .none in your style.css then you can add to addTaskBtn

2021-05-28 14:01 UTC, bellom requested changes
## Hi Team  :clap: 

**Great work making adding all the necessary features mentioned by the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-05-28 14:01 UTC, bellom commented on dist/index.html
> +    </div> -->
Remove commented code;
You need to remove the commented code, It’s better to delete the commented code. If you need to review a previous version of your code, use git history.

2021-05-28 14:01 UTC, bellom commented on dist/index.html
> +  </script> -->
Remove commented code;

2021-05-28 14:01 UTC, bellom commented on src/dom.js
> +    // const liststasks = JSON.parse(localStorage.liststore);
Remove commented code

2021-05-28 15:18 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔**

Project approved.
Great work.
You can merge and move on to other projects.👏👏👏

Happy coding💻💻💻

2021-05-28 15:28 UTC, merged